# Generated by Django 5.2.4 on 2025-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_alter_question_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
